# Generated by Django 2.2.24 on 2022-04-19 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('decimals', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('Token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Token')),
            ],
        ),
    ]
