# Generated by Django 4.0.4 on 2022-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pixiu',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
