# Generated by Django 4.0.4 on 2022-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_bill',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
