# Generated by Django 4.0.4 on 2022-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_token_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp',
            fields=[
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
