# Generated by Django 4.0.4 on 2022-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lp'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='isLp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
